package com.edreaminfo.cbas.orm.model;

public class EventInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_id
     *
     * @mbggenerated
     */
    private Integer event_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_en
     *
     * @mbggenerated
     */
    private String event_en;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_cn
     *
     * @mbggenerated
     */
    private String event_cn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.page_id
     *
     * @mbggenerated
     */
    private Integer page_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.linked_page_id
     *
     * @mbggenerated
     */
    private Integer linked_page_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.object
     *
     * @mbggenerated
     */
    private Integer object;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.important
     *
     * @mbggenerated
     */
    private Byte important;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.pos_x
     *
     * @mbggenerated
     */
    private Integer pos_x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.pos_y
     *
     * @mbggenerated
     */
    private Integer pos_y;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.id
     *
     * @return the value of event_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.id
     *
     * @param id the value for event_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_id
     *
     * @return the value of event_info.event_id
     *
     * @mbggenerated
     */
    public Integer getEvent_id() {
        return event_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_id
     *
     * @param event_id the value for event_info.event_id
     *
     * @mbggenerated
     */
    public void setEvent_id(Integer event_id) {
        this.event_id = event_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_en
     *
     * @return the value of event_info.event_en
     *
     * @mbggenerated
     */
    public String getEvent_en() {
        return event_en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_en
     *
     * @param event_en the value for event_info.event_en
     *
     * @mbggenerated
     */
    public void setEvent_en(String event_en) {
        this.event_en = event_en == null ? null : event_en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_cn
     *
     * @return the value of event_info.event_cn
     *
     * @mbggenerated
     */
    public String getEvent_cn() {
        return event_cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_cn
     *
     * @param event_cn the value for event_info.event_cn
     *
     * @mbggenerated
     */
    public void setEvent_cn(String event_cn) {
        this.event_cn = event_cn == null ? null : event_cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.description
     *
     * @return the value of event_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.description
     *
     * @param description the value for event_info.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.type
     *
     * @return the value of event_info.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.type
     *
     * @param type the value for event_info.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.page_id
     *
     * @return the value of event_info.page_id
     *
     * @mbggenerated
     */
    public Integer getPage_id() {
        return page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.page_id
     *
     * @param page_id the value for event_info.page_id
     *
     * @mbggenerated
     */
    public void setPage_id(Integer page_id) {
        this.page_id = page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.linked_page_id
     *
     * @return the value of event_info.linked_page_id
     *
     * @mbggenerated
     */
    public Integer getLinked_page_id() {
        return linked_page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.linked_page_id
     *
     * @param linked_page_id the value for event_info.linked_page_id
     *
     * @mbggenerated
     */
    public void setLinked_page_id(Integer linked_page_id) {
        this.linked_page_id = linked_page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.object
     *
     * @return the value of event_info.object
     *
     * @mbggenerated
     */
    public Integer getObject() {
        return object;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.object
     *
     * @param object the value for event_info.object
     *
     * @mbggenerated
     */
    public void setObject(Integer object) {
        this.object = object;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.important
     *
     * @return the value of event_info.important
     *
     * @mbggenerated
     */
    public Byte getImportant() {
        return important;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.important
     *
     * @param important the value for event_info.important
     *
     * @mbggenerated
     */
    public void setImportant(Byte important) {
        this.important = important;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.pos_x
     *
     * @return the value of event_info.pos_x
     *
     * @mbggenerated
     */
    public Integer getPos_x() {
        return pos_x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.pos_x
     *
     * @param pos_x the value for event_info.pos_x
     *
     * @mbggenerated
     */
    public void setPos_x(Integer pos_x) {
        this.pos_x = pos_x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.pos_y
     *
     * @return the value of event_info.pos_y
     *
     * @mbggenerated
     */
    public Integer getPos_y() {
        return pos_y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.pos_y
     *
     * @param pos_y the value for event_info.pos_y
     *
     * @mbggenerated
     */
    public void setPos_y(Integer pos_y) {
        this.pos_y = pos_y;
    }
}