package com.edreaminfo.cbas.orm.model;

import java.util.Date;

public class EventdoLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdo_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdo_log.eventdo_id
     *
     * @mbggenerated
     */
    private Integer eventdo_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdo_log.event_id
     *
     * @mbggenerated
     */
    private Integer event_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdo_log.pageview_id
     *
     * @mbggenerated
     */
    private Integer pageview_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdo_log.session_id
     *
     * @mbggenerated
     */
    private Integer session_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdo_log.eventdo_datetime
     *
     * @mbggenerated
     */
    private Date eventdo_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdo_log.Eventdo_msecond
     *
     * @mbggenerated
     */
    private Integer eventdo_msecond;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdo_log.id
     *
     * @return the value of eventdo_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdo_log.id
     *
     * @param id the value for eventdo_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdo_log.eventdo_id
     *
     * @return the value of eventdo_log.eventdo_id
     *
     * @mbggenerated
     */
    public Integer getEventdo_id() {
        return eventdo_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdo_log.eventdo_id
     *
     * @param eventdo_id the value for eventdo_log.eventdo_id
     *
     * @mbggenerated
     */
    public void setEventdo_id(Integer eventdo_id) {
        this.eventdo_id = eventdo_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdo_log.event_id
     *
     * @return the value of eventdo_log.event_id
     *
     * @mbggenerated
     */
    public Integer getEvent_id() {
        return event_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdo_log.event_id
     *
     * @param event_id the value for eventdo_log.event_id
     *
     * @mbggenerated
     */
    public void setEvent_id(Integer event_id) {
        this.event_id = event_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdo_log.pageview_id
     *
     * @return the value of eventdo_log.pageview_id
     *
     * @mbggenerated
     */
    public Integer getPageview_id() {
        return pageview_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdo_log.pageview_id
     *
     * @param pageview_id the value for eventdo_log.pageview_id
     *
     * @mbggenerated
     */
    public void setPageview_id(Integer pageview_id) {
        this.pageview_id = pageview_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdo_log.session_id
     *
     * @return the value of eventdo_log.session_id
     *
     * @mbggenerated
     */
    public Integer getSession_id() {
        return session_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdo_log.session_id
     *
     * @param session_id the value for eventdo_log.session_id
     *
     * @mbggenerated
     */
    public void setSession_id(Integer session_id) {
        this.session_id = session_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdo_log.eventdo_datetime
     *
     * @return the value of eventdo_log.eventdo_datetime
     *
     * @mbggenerated
     */
    public Date getEventdo_datetime() {
        return eventdo_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdo_log.eventdo_datetime
     *
     * @param eventdo_datetime the value for eventdo_log.eventdo_datetime
     *
     * @mbggenerated
     */
    public void setEventdo_datetime(Date eventdo_datetime) {
        this.eventdo_datetime = eventdo_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdo_log.Eventdo_msecond
     *
     * @return the value of eventdo_log.Eventdo_msecond
     *
     * @mbggenerated
     */
    public Integer getEventdo_msecond() {
        return eventdo_msecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdo_log.Eventdo_msecond
     *
     * @param eventdo_msecond the value for eventdo_log.Eventdo_msecond
     *
     * @mbggenerated
     */
    public void setEventdo_msecond(Integer eventdo_msecond) {
        this.eventdo_msecond = eventdo_msecond;
    }
}