package com.edreaminfo.cbas.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PageviewLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public PageviewLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPageview_idIsNull() {
            addCriterion("pageview_id is null");
            return (Criteria) this;
        }

        public Criteria andPageview_idIsNotNull() {
            addCriterion("pageview_id is not null");
            return (Criteria) this;
        }

        public Criteria andPageview_idEqualTo(Integer value) {
            addCriterion("pageview_id =", value, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idNotEqualTo(Integer value) {
            addCriterion("pageview_id <>", value, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idGreaterThan(Integer value) {
            addCriterion("pageview_id >", value, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("pageview_id >=", value, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idLessThan(Integer value) {
            addCriterion("pageview_id <", value, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idLessThanOrEqualTo(Integer value) {
            addCriterion("pageview_id <=", value, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idIn(List<Integer> values) {
            addCriterion("pageview_id in", values, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idNotIn(List<Integer> values) {
            addCriterion("pageview_id not in", values, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idBetween(Integer value1, Integer value2) {
            addCriterion("pageview_id between", value1, value2, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPageview_idNotBetween(Integer value1, Integer value2) {
            addCriterion("pageview_id not between", value1, value2, "pageview_id");
            return (Criteria) this;
        }

        public Criteria andPage_idIsNull() {
            addCriterion("page_id is null");
            return (Criteria) this;
        }

        public Criteria andPage_idIsNotNull() {
            addCriterion("page_id is not null");
            return (Criteria) this;
        }

        public Criteria andPage_idEqualTo(Integer value) {
            addCriterion("page_id =", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idNotEqualTo(Integer value) {
            addCriterion("page_id <>", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idGreaterThan(Integer value) {
            addCriterion("page_id >", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_id >=", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idLessThan(Integer value) {
            addCriterion("page_id <", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idLessThanOrEqualTo(Integer value) {
            addCriterion("page_id <=", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idIn(List<Integer> values) {
            addCriterion("page_id in", values, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idNotIn(List<Integer> values) {
            addCriterion("page_id not in", values, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idBetween(Integer value1, Integer value2) {
            addCriterion("page_id between", value1, value2, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idNotBetween(Integer value1, Integer value2) {
            addCriterion("page_id not between", value1, value2, "page_id");
            return (Criteria) this;
        }

        public Criteria andSession_idIsNull() {
            addCriterion("session_id is null");
            return (Criteria) this;
        }

        public Criteria andSession_idIsNotNull() {
            addCriterion("session_id is not null");
            return (Criteria) this;
        }

        public Criteria andSession_idEqualTo(Integer value) {
            addCriterion("session_id =", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idNotEqualTo(Integer value) {
            addCriterion("session_id <>", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idGreaterThan(Integer value) {
            addCriterion("session_id >", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("session_id >=", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idLessThan(Integer value) {
            addCriterion("session_id <", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idLessThanOrEqualTo(Integer value) {
            addCriterion("session_id <=", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idIn(List<Integer> values) {
            addCriterion("session_id in", values, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idNotIn(List<Integer> values) {
            addCriterion("session_id not in", values, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idBetween(Integer value1, Integer value2) {
            addCriterion("session_id between", value1, value2, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idNotBetween(Integer value1, Integer value2) {
            addCriterion("session_id not between", value1, value2, "session_id");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtIsNull() {
            addCriterion("pageview_start_dt is null");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtIsNotNull() {
            addCriterion("pageview_start_dt is not null");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtEqualTo(Date value) {
            addCriterion("pageview_start_dt =", value, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtNotEqualTo(Date value) {
            addCriterion("pageview_start_dt <>", value, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtGreaterThan(Date value) {
            addCriterion("pageview_start_dt >", value, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtGreaterThanOrEqualTo(Date value) {
            addCriterion("pageview_start_dt >=", value, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtLessThan(Date value) {
            addCriterion("pageview_start_dt <", value, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtLessThanOrEqualTo(Date value) {
            addCriterion("pageview_start_dt <=", value, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtIn(List<Date> values) {
            addCriterion("pageview_start_dt in", values, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtNotIn(List<Date> values) {
            addCriterion("pageview_start_dt not in", values, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtBetween(Date value1, Date value2) {
            addCriterion("pageview_start_dt between", value1, value2, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_start_dtNotBetween(Date value1, Date value2) {
            addCriterion("pageview_start_dt not between", value1, value2, "pageview_start_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtIsNull() {
            addCriterion("pageview_end_dt is null");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtIsNotNull() {
            addCriterion("pageview_end_dt is not null");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtEqualTo(Date value) {
            addCriterion("pageview_end_dt =", value, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtNotEqualTo(Date value) {
            addCriterion("pageview_end_dt <>", value, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtGreaterThan(Date value) {
            addCriterion("pageview_end_dt >", value, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtGreaterThanOrEqualTo(Date value) {
            addCriterion("pageview_end_dt >=", value, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtLessThan(Date value) {
            addCriterion("pageview_end_dt <", value, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtLessThanOrEqualTo(Date value) {
            addCriterion("pageview_end_dt <=", value, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtIn(List<Date> values) {
            addCriterion("pageview_end_dt in", values, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtNotIn(List<Date> values) {
            addCriterion("pageview_end_dt not in", values, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtBetween(Date value1, Date value2) {
            addCriterion("pageview_end_dt between", value1, value2, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_end_dtNotBetween(Date value1, Date value2) {
            addCriterion("pageview_end_dt not between", value1, value2, "pageview_end_dt");
            return (Criteria) this;
        }

        public Criteria andPageview_durationIsNull() {
            addCriterion("Pageview_duration is null");
            return (Criteria) this;
        }

        public Criteria andPageview_durationIsNotNull() {
            addCriterion("Pageview_duration is not null");
            return (Criteria) this;
        }

        public Criteria andPageview_durationEqualTo(Integer value) {
            addCriterion("Pageview_duration =", value, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationNotEqualTo(Integer value) {
            addCriterion("Pageview_duration <>", value, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationGreaterThan(Integer value) {
            addCriterion("Pageview_duration >", value, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationGreaterThanOrEqualTo(Integer value) {
            addCriterion("Pageview_duration >=", value, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationLessThan(Integer value) {
            addCriterion("Pageview_duration <", value, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationLessThanOrEqualTo(Integer value) {
            addCriterion("Pageview_duration <=", value, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationIn(List<Integer> values) {
            addCriterion("Pageview_duration in", values, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationNotIn(List<Integer> values) {
            addCriterion("Pageview_duration not in", values, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationBetween(Integer value1, Integer value2) {
            addCriterion("Pageview_duration between", value1, value2, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_durationNotBetween(Integer value1, Integer value2) {
            addCriterion("Pageview_duration not between", value1, value2, "pageview_duration");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntIsNull() {
            addCriterion("eventdo_cnt is null");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntIsNotNull() {
            addCriterion("eventdo_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntEqualTo(Integer value) {
            addCriterion("eventdo_cnt =", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntNotEqualTo(Integer value) {
            addCriterion("eventdo_cnt <>", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntGreaterThan(Integer value) {
            addCriterion("eventdo_cnt >", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntGreaterThanOrEqualTo(Integer value) {
            addCriterion("eventdo_cnt >=", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntLessThan(Integer value) {
            addCriterion("eventdo_cnt <", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntLessThanOrEqualTo(Integer value) {
            addCriterion("eventdo_cnt <=", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntIn(List<Integer> values) {
            addCriterion("eventdo_cnt in", values, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntNotIn(List<Integer> values) {
            addCriterion("eventdo_cnt not in", values, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntBetween(Integer value1, Integer value2) {
            addCriterion("eventdo_cnt between", value1, value2, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntNotBetween(Integer value1, Integer value2) {
            addCriterion("eventdo_cnt not between", value1, value2, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_quitIsNull() {
            addCriterion("pageview_quit is null");
            return (Criteria) this;
        }

        public Criteria andPageview_quitIsNotNull() {
            addCriterion("pageview_quit is not null");
            return (Criteria) this;
        }

        public Criteria andPageview_quitEqualTo(Byte value) {
            addCriterion("pageview_quit =", value, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitNotEqualTo(Byte value) {
            addCriterion("pageview_quit <>", value, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitGreaterThan(Byte value) {
            addCriterion("pageview_quit >", value, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitGreaterThanOrEqualTo(Byte value) {
            addCriterion("pageview_quit >=", value, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitLessThan(Byte value) {
            addCriterion("pageview_quit <", value, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitLessThanOrEqualTo(Byte value) {
            addCriterion("pageview_quit <=", value, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitIn(List<Byte> values) {
            addCriterion("pageview_quit in", values, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitNotIn(List<Byte> values) {
            addCriterion("pageview_quit not in", values, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitBetween(Byte value1, Byte value2) {
            addCriterion("pageview_quit between", value1, value2, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andPageview_quitNotBetween(Byte value1, Byte value2) {
            addCriterion("pageview_quit not between", value1, value2, "pageview_quit");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idIsNull() {
            addCriterion("first_event_id is null");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idIsNotNull() {
            addCriterion("first_event_id is not null");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idEqualTo(Integer value) {
            addCriterion("first_event_id =", value, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idNotEqualTo(Integer value) {
            addCriterion("first_event_id <>", value, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idGreaterThan(Integer value) {
            addCriterion("first_event_id >", value, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_event_id >=", value, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idLessThan(Integer value) {
            addCriterion("first_event_id <", value, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idLessThanOrEqualTo(Integer value) {
            addCriterion("first_event_id <=", value, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idIn(List<Integer> values) {
            addCriterion("first_event_id in", values, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idNotIn(List<Integer> values) {
            addCriterion("first_event_id not in", values, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idBetween(Integer value1, Integer value2) {
            addCriterion("first_event_id between", value1, value2, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_idNotBetween(Integer value1, Integer value2) {
            addCriterion("first_event_id not between", value1, value2, "first_event_id");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationIsNull() {
            addCriterion("first_event_duration is null");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationIsNotNull() {
            addCriterion("first_event_duration is not null");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationEqualTo(Integer value) {
            addCriterion("first_event_duration =", value, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationNotEqualTo(Integer value) {
            addCriterion("first_event_duration <>", value, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationGreaterThan(Integer value) {
            addCriterion("first_event_duration >", value, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_event_duration >=", value, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationLessThan(Integer value) {
            addCriterion("first_event_duration <", value, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationLessThanOrEqualTo(Integer value) {
            addCriterion("first_event_duration <=", value, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationIn(List<Integer> values) {
            addCriterion("first_event_duration in", values, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationNotIn(List<Integer> values) {
            addCriterion("first_event_duration not in", values, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationBetween(Integer value1, Integer value2) {
            addCriterion("first_event_duration between", value1, value2, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andFirst_event_durationNotBetween(Integer value1, Integer value2) {
            addCriterion("first_event_duration not between", value1, value2, "first_event_duration");
            return (Criteria) this;
        }

        public Criteria andLast_event_idIsNull() {
            addCriterion("last_event_id is null");
            return (Criteria) this;
        }

        public Criteria andLast_event_idIsNotNull() {
            addCriterion("last_event_id is not null");
            return (Criteria) this;
        }

        public Criteria andLast_event_idEqualTo(Integer value) {
            addCriterion("last_event_id =", value, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idNotEqualTo(Integer value) {
            addCriterion("last_event_id <>", value, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idGreaterThan(Integer value) {
            addCriterion("last_event_id >", value, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_event_id >=", value, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idLessThan(Integer value) {
            addCriterion("last_event_id <", value, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idLessThanOrEqualTo(Integer value) {
            addCriterion("last_event_id <=", value, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idIn(List<Integer> values) {
            addCriterion("last_event_id in", values, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idNotIn(List<Integer> values) {
            addCriterion("last_event_id not in", values, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idBetween(Integer value1, Integer value2) {
            addCriterion("last_event_id between", value1, value2, "last_event_id");
            return (Criteria) this;
        }

        public Criteria andLast_event_idNotBetween(Integer value1, Integer value2) {
            addCriterion("last_event_id not between", value1, value2, "last_event_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pageview_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pageview_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}