package com.edreaminfo.cbas.orm.model;

public class PageInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.page_id
     *
     * @mbggenerated
     */
    private Integer page_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.page_en
     *
     * @mbggenerated
     */
    private String page_en;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.page_cn
     *
     * @mbggenerated
     */
    private String page_cn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.page_type
     *
     * @mbggenerated
     */
    private String page_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.depth
     *
     * @mbggenerated
     */
    private Byte depth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_info.business
     *
     * @mbggenerated
     */
    private String business;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.id
     *
     * @return the value of page_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.id
     *
     * @param id the value for page_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.page_id
     *
     * @return the value of page_info.page_id
     *
     * @mbggenerated
     */
    public Integer getPage_id() {
        return page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.page_id
     *
     * @param page_id the value for page_info.page_id
     *
     * @mbggenerated
     */
    public void setPage_id(Integer page_id) {
        this.page_id = page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.page_en
     *
     * @return the value of page_info.page_en
     *
     * @mbggenerated
     */
    public String getPage_en() {
        return page_en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.page_en
     *
     * @param page_en the value for page_info.page_en
     *
     * @mbggenerated
     */
    public void setPage_en(String page_en) {
        this.page_en = page_en == null ? null : page_en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.page_cn
     *
     * @return the value of page_info.page_cn
     *
     * @mbggenerated
     */
    public String getPage_cn() {
        return page_cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.page_cn
     *
     * @param page_cn the value for page_info.page_cn
     *
     * @mbggenerated
     */
    public void setPage_cn(String page_cn) {
        this.page_cn = page_cn == null ? null : page_cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.description
     *
     * @return the value of page_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.description
     *
     * @param description the value for page_info.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.page_type
     *
     * @return the value of page_info.page_type
     *
     * @mbggenerated
     */
    public String getPage_type() {
        return page_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.page_type
     *
     * @param page_type the value for page_info.page_type
     *
     * @mbggenerated
     */
    public void setPage_type(String page_type) {
        this.page_type = page_type == null ? null : page_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.depth
     *
     * @return the value of page_info.depth
     *
     * @mbggenerated
     */
    public Byte getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.depth
     *
     * @param depth the value for page_info.depth
     *
     * @mbggenerated
     */
    public void setDepth(Byte depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_info.business
     *
     * @return the value of page_info.business
     *
     * @mbggenerated
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_info.business
     *
     * @param business the value for page_info.business
     *
     * @mbggenerated
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }
}