package com.edreaminfo.cbas.orm.model;

import java.util.Date;

public class PageviewDayStats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.dt
     *
     * @mbggenerated
     */
    private Date dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.page_id
     *
     * @mbggenerated
     */
    private Integer page_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.pageview_cnt
     *
     * @mbggenerated
     */
    private Integer pageview_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.session_cnt
     *
     * @mbggenerated
     */
    private Integer session_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.pageview_duration_sum
     *
     * @mbggenerated
     */
    private Integer pageview_duration_sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.eventdo_cnt_sum
     *
     * @mbggenerated
     */
    private Integer eventdo_cnt_sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.pageview_quit_sum
     *
     * @mbggenerated
     */
    private Integer pageview_quit_sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.channel_id
     *
     * @mbggenerated
     */
    private Integer channel_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.version_id
     *
     * @mbggenerated
     */
    private Integer version_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageview_day_stats.user_type_id
     *
     * @mbggenerated
     */
    private Integer user_type_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.id
     *
     * @return the value of pageview_day_stats.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.id
     *
     * @param id the value for pageview_day_stats.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.dt
     *
     * @return the value of pageview_day_stats.dt
     *
     * @mbggenerated
     */
    public Date getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.dt
     *
     * @param dt the value for pageview_day_stats.dt
     *
     * @mbggenerated
     */
    public void setDt(Date dt) {
        this.dt = dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.page_id
     *
     * @return the value of pageview_day_stats.page_id
     *
     * @mbggenerated
     */
    public Integer getPage_id() {
        return page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.page_id
     *
     * @param page_id the value for pageview_day_stats.page_id
     *
     * @mbggenerated
     */
    public void setPage_id(Integer page_id) {
        this.page_id = page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.pageview_cnt
     *
     * @return the value of pageview_day_stats.pageview_cnt
     *
     * @mbggenerated
     */
    public Integer getPageview_cnt() {
        return pageview_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.pageview_cnt
     *
     * @param pageview_cnt the value for pageview_day_stats.pageview_cnt
     *
     * @mbggenerated
     */
    public void setPageview_cnt(Integer pageview_cnt) {
        this.pageview_cnt = pageview_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.session_cnt
     *
     * @return the value of pageview_day_stats.session_cnt
     *
     * @mbggenerated
     */
    public Integer getSession_cnt() {
        return session_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.session_cnt
     *
     * @param session_cnt the value for pageview_day_stats.session_cnt
     *
     * @mbggenerated
     */
    public void setSession_cnt(Integer session_cnt) {
        this.session_cnt = session_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.pageview_duration_sum
     *
     * @return the value of pageview_day_stats.pageview_duration_sum
     *
     * @mbggenerated
     */
    public Integer getPageview_duration_sum() {
        return pageview_duration_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.pageview_duration_sum
     *
     * @param pageview_duration_sum the value for pageview_day_stats.pageview_duration_sum
     *
     * @mbggenerated
     */
    public void setPageview_duration_sum(Integer pageview_duration_sum) {
        this.pageview_duration_sum = pageview_duration_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.eventdo_cnt_sum
     *
     * @return the value of pageview_day_stats.eventdo_cnt_sum
     *
     * @mbggenerated
     */
    public Integer getEventdo_cnt_sum() {
        return eventdo_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.eventdo_cnt_sum
     *
     * @param eventdo_cnt_sum the value for pageview_day_stats.eventdo_cnt_sum
     *
     * @mbggenerated
     */
    public void setEventdo_cnt_sum(Integer eventdo_cnt_sum) {
        this.eventdo_cnt_sum = eventdo_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.pageview_quit_sum
     *
     * @return the value of pageview_day_stats.pageview_quit_sum
     *
     * @mbggenerated
     */
    public Integer getPageview_quit_sum() {
        return pageview_quit_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.pageview_quit_sum
     *
     * @param pageview_quit_sum the value for pageview_day_stats.pageview_quit_sum
     *
     * @mbggenerated
     */
    public void setPageview_quit_sum(Integer pageview_quit_sum) {
        this.pageview_quit_sum = pageview_quit_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.channel_id
     *
     * @return the value of pageview_day_stats.channel_id
     *
     * @mbggenerated
     */
    public Integer getChannel_id() {
        return channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.channel_id
     *
     * @param channel_id the value for pageview_day_stats.channel_id
     *
     * @mbggenerated
     */
    public void setChannel_id(Integer channel_id) {
        this.channel_id = channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.version_id
     *
     * @return the value of pageview_day_stats.version_id
     *
     * @mbggenerated
     */
    public Integer getVersion_id() {
        return version_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.version_id
     *
     * @param version_id the value for pageview_day_stats.version_id
     *
     * @mbggenerated
     */
    public void setVersion_id(Integer version_id) {
        this.version_id = version_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageview_day_stats.user_type_id
     *
     * @return the value of pageview_day_stats.user_type_id
     *
     * @mbggenerated
     */
    public Integer getUser_type_id() {
        return user_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageview_day_stats.user_type_id
     *
     * @param user_type_id the value for pageview_day_stats.user_type_id
     *
     * @mbggenerated
     */
    public void setUser_type_id(Integer user_type_id) {
        this.user_type_id = user_type_id;
    }
}