package com.edreaminfo.cbas.orm.model;

import java.util.ArrayList;
import java.util.List;

public class PageInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public PageInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPage_idIsNull() {
            addCriterion("page_id is null");
            return (Criteria) this;
        }

        public Criteria andPage_idIsNotNull() {
            addCriterion("page_id is not null");
            return (Criteria) this;
        }

        public Criteria andPage_idEqualTo(Integer value) {
            addCriterion("page_id =", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idNotEqualTo(Integer value) {
            addCriterion("page_id <>", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idGreaterThan(Integer value) {
            addCriterion("page_id >", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_id >=", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idLessThan(Integer value) {
            addCriterion("page_id <", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idLessThanOrEqualTo(Integer value) {
            addCriterion("page_id <=", value, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idIn(List<Integer> values) {
            addCriterion("page_id in", values, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idNotIn(List<Integer> values) {
            addCriterion("page_id not in", values, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idBetween(Integer value1, Integer value2) {
            addCriterion("page_id between", value1, value2, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_idNotBetween(Integer value1, Integer value2) {
            addCriterion("page_id not between", value1, value2, "page_id");
            return (Criteria) this;
        }

        public Criteria andPage_enIsNull() {
            addCriterion("page_en is null");
            return (Criteria) this;
        }

        public Criteria andPage_enIsNotNull() {
            addCriterion("page_en is not null");
            return (Criteria) this;
        }

        public Criteria andPage_enEqualTo(String value) {
            addCriterion("page_en =", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enNotEqualTo(String value) {
            addCriterion("page_en <>", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enGreaterThan(String value) {
            addCriterion("page_en >", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enGreaterThanOrEqualTo(String value) {
            addCriterion("page_en >=", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enLessThan(String value) {
            addCriterion("page_en <", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enLessThanOrEqualTo(String value) {
            addCriterion("page_en <=", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enLike(String value) {
            addCriterion("page_en like", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enNotLike(String value) {
            addCriterion("page_en not like", value, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enIn(List<String> values) {
            addCriterion("page_en in", values, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enNotIn(List<String> values) {
            addCriterion("page_en not in", values, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enBetween(String value1, String value2) {
            addCriterion("page_en between", value1, value2, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_enNotBetween(String value1, String value2) {
            addCriterion("page_en not between", value1, value2, "page_en");
            return (Criteria) this;
        }

        public Criteria andPage_cnIsNull() {
            addCriterion("page_cn is null");
            return (Criteria) this;
        }

        public Criteria andPage_cnIsNotNull() {
            addCriterion("page_cn is not null");
            return (Criteria) this;
        }

        public Criteria andPage_cnEqualTo(String value) {
            addCriterion("page_cn =", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnNotEqualTo(String value) {
            addCriterion("page_cn <>", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnGreaterThan(String value) {
            addCriterion("page_cn >", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnGreaterThanOrEqualTo(String value) {
            addCriterion("page_cn >=", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnLessThan(String value) {
            addCriterion("page_cn <", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnLessThanOrEqualTo(String value) {
            addCriterion("page_cn <=", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnLike(String value) {
            addCriterion("page_cn like", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnNotLike(String value) {
            addCriterion("page_cn not like", value, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnIn(List<String> values) {
            addCriterion("page_cn in", values, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnNotIn(List<String> values) {
            addCriterion("page_cn not in", values, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnBetween(String value1, String value2) {
            addCriterion("page_cn between", value1, value2, "page_cn");
            return (Criteria) this;
        }

        public Criteria andPage_cnNotBetween(String value1, String value2) {
            addCriterion("page_cn not between", value1, value2, "page_cn");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andPage_typeIsNull() {
            addCriterion("page_type is null");
            return (Criteria) this;
        }

        public Criteria andPage_typeIsNotNull() {
            addCriterion("page_type is not null");
            return (Criteria) this;
        }

        public Criteria andPage_typeEqualTo(String value) {
            addCriterion("page_type =", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeNotEqualTo(String value) {
            addCriterion("page_type <>", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeGreaterThan(String value) {
            addCriterion("page_type >", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeGreaterThanOrEqualTo(String value) {
            addCriterion("page_type >=", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeLessThan(String value) {
            addCriterion("page_type <", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeLessThanOrEqualTo(String value) {
            addCriterion("page_type <=", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeLike(String value) {
            addCriterion("page_type like", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeNotLike(String value) {
            addCriterion("page_type not like", value, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeIn(List<String> values) {
            addCriterion("page_type in", values, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeNotIn(List<String> values) {
            addCriterion("page_type not in", values, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeBetween(String value1, String value2) {
            addCriterion("page_type between", value1, value2, "page_type");
            return (Criteria) this;
        }

        public Criteria andPage_typeNotBetween(String value1, String value2) {
            addCriterion("page_type not between", value1, value2, "page_type");
            return (Criteria) this;
        }

        public Criteria andDepthIsNull() {
            addCriterion("depth is null");
            return (Criteria) this;
        }

        public Criteria andDepthIsNotNull() {
            addCriterion("depth is not null");
            return (Criteria) this;
        }

        public Criteria andDepthEqualTo(Byte value) {
            addCriterion("depth =", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthNotEqualTo(Byte value) {
            addCriterion("depth <>", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthGreaterThan(Byte value) {
            addCriterion("depth >", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthGreaterThanOrEqualTo(Byte value) {
            addCriterion("depth >=", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthLessThan(Byte value) {
            addCriterion("depth <", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthLessThanOrEqualTo(Byte value) {
            addCriterion("depth <=", value, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthIn(List<Byte> values) {
            addCriterion("depth in", values, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthNotIn(List<Byte> values) {
            addCriterion("depth not in", values, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthBetween(Byte value1, Byte value2) {
            addCriterion("depth between", value1, value2, "depth");
            return (Criteria) this;
        }

        public Criteria andDepthNotBetween(Byte value1, Byte value2) {
            addCriterion("depth not between", value1, value2, "depth");
            return (Criteria) this;
        }

        public Criteria andBusinessIsNull() {
            addCriterion("business is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIsNotNull() {
            addCriterion("business is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessEqualTo(String value) {
            addCriterion("business =", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotEqualTo(String value) {
            addCriterion("business <>", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessGreaterThan(String value) {
            addCriterion("business >", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessGreaterThanOrEqualTo(String value) {
            addCriterion("business >=", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLessThan(String value) {
            addCriterion("business <", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLessThanOrEqualTo(String value) {
            addCriterion("business <=", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLike(String value) {
            addCriterion("business like", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotLike(String value) {
            addCriterion("business not like", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessIn(List<String> values) {
            addCriterion("business in", values, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotIn(List<String> values) {
            addCriterion("business not in", values, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessBetween(String value1, String value2) {
            addCriterion("business between", value1, value2, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotBetween(String value1, String value2) {
            addCriterion("business not between", value1, value2, "business");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}