package com.edreaminfo.cbas.orm.model;

public class RelationBusinessPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_business_page.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_business_page.business_id
     *
     * @mbggenerated
     */
    private Integer business_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_business_page.page_id
     *
     * @mbggenerated
     */
    private Integer page_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_business_page.id
     *
     * @return the value of relation_business_page.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_business_page.id
     *
     * @param id the value for relation_business_page.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_business_page.business_id
     *
     * @return the value of relation_business_page.business_id
     *
     * @mbggenerated
     */
    public Integer getBusiness_id() {
        return business_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_business_page.business_id
     *
     * @param business_id the value for relation_business_page.business_id
     *
     * @mbggenerated
     */
    public void setBusiness_id(Integer business_id) {
        this.business_id = business_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_business_page.page_id
     *
     * @return the value of relation_business_page.page_id
     *
     * @mbggenerated
     */
    public Integer getPage_id() {
        return page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_business_page.page_id
     *
     * @param page_id the value for relation_business_page.page_id
     *
     * @mbggenerated
     */
    public void setPage_id(Integer page_id) {
        this.page_id = page_id;
    }
}