package com.edreaminfo.cbas.orm.model;

public class RelationEventgroupPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_pagegroup_page.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_pagegroup_page.pagegroup_id
     *
     * @mbggenerated
     */
    private Integer pagegroup_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_pagegroup_page.page_id
     *
     * @mbggenerated
     */
    private Integer page_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_pagegroup_page.id
     *
     * @return the value of relation_pagegroup_page.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_pagegroup_page.id
     *
     * @param id the value for relation_pagegroup_page.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_pagegroup_page.pagegroup_id
     *
     * @return the value of relation_pagegroup_page.pagegroup_id
     *
     * @mbggenerated
     */
    public Integer getPagegroup_id() {
        return pagegroup_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_pagegroup_page.pagegroup_id
     *
     * @param pagegroup_id the value for relation_pagegroup_page.pagegroup_id
     *
     * @mbggenerated
     */
    public void setPagegroup_id(Integer pagegroup_id) {
        this.pagegroup_id = pagegroup_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_pagegroup_page.page_id
     *
     * @return the value of relation_pagegroup_page.page_id
     *
     * @mbggenerated
     */
    public Integer getPage_id() {
        return page_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_pagegroup_page.page_id
     *
     * @param page_id the value for relation_pagegroup_page.page_id
     *
     * @mbggenerated
     */
    public void setPage_id(Integer page_id) {
        this.page_id = page_id;
    }
}