package com.edreaminfo.cbas.orm.model;

public class RelationBusinessPagegroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_business_pagegroup.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_business_pagegroup.pagegroup_id
     *
     * @mbggenerated
     */
    private Integer pagegroup_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_business_pagegroup.business_id
     *
     * @mbggenerated
     */
    private Integer business_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_business_pagegroup.id
     *
     * @return the value of relation_business_pagegroup.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_business_pagegroup.id
     *
     * @param id the value for relation_business_pagegroup.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_business_pagegroup.pagegroup_id
     *
     * @return the value of relation_business_pagegroup.pagegroup_id
     *
     * @mbggenerated
     */
    public Integer getPagegroup_id() {
        return pagegroup_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_business_pagegroup.pagegroup_id
     *
     * @param pagegroup_id the value for relation_business_pagegroup.pagegroup_id
     *
     * @mbggenerated
     */
    public void setPagegroup_id(Integer pagegroup_id) {
        this.pagegroup_id = pagegroup_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_business_pagegroup.business_id
     *
     * @return the value of relation_business_pagegroup.business_id
     *
     * @mbggenerated
     */
    public Integer getBusiness_id() {
        return business_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_business_pagegroup.business_id
     *
     * @param business_id the value for relation_business_pagegroup.business_id
     *
     * @mbggenerated
     */
    public void setBusiness_id(Integer business_id) {
        this.business_id = business_id;
    }
}