package com.edreaminfo.cbas.orm.model;

import java.util.Date;

public class SessionDayStats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.dt
     *
     * @mbggenerated
     */
    private Date dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.session_cnt
     *
     * @mbggenerated
     */
    private Integer session_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.user_cnt
     *
     * @mbggenerated
     */
    private Integer user_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.ip_cnt
     *
     * @mbggenerated
     */
    private Integer ip_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.session_duration_sum
     *
     * @mbggenerated
     */
    private Integer session_duration_sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.pageview_cnt_sum
     *
     * @mbggenerated
     */
    private Integer pageview_cnt_sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.page_cnt_sum
     *
     * @mbggenerated
     */
    private Integer page_cnt_sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.eventdo_cnt_sum
     *
     * @mbggenerated
     */
    private Integer eventdo_cnt_sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_day_stats.user_session_cnt
     *
     * @mbggenerated
     */
    private Double user_session_cnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.id
     *
     * @return the value of session_day_stats.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.id
     *
     * @param id the value for session_day_stats.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.dt
     *
     * @return the value of session_day_stats.dt
     *
     * @mbggenerated
     */
    public Date getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.dt
     *
     * @param dt the value for session_day_stats.dt
     *
     * @mbggenerated
     */
    public void setDt(Date dt) {
        this.dt = dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.session_cnt
     *
     * @return the value of session_day_stats.session_cnt
     *
     * @mbggenerated
     */
    public Integer getSession_cnt() {
        return session_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.session_cnt
     *
     * @param session_cnt the value for session_day_stats.session_cnt
     *
     * @mbggenerated
     */
    public void setSession_cnt(Integer session_cnt) {
        this.session_cnt = session_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.user_cnt
     *
     * @return the value of session_day_stats.user_cnt
     *
     * @mbggenerated
     */
    public Integer getUser_cnt() {
        return user_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.user_cnt
     *
     * @param user_cnt the value for session_day_stats.user_cnt
     *
     * @mbggenerated
     */
    public void setUser_cnt(Integer user_cnt) {
        this.user_cnt = user_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.ip_cnt
     *
     * @return the value of session_day_stats.ip_cnt
     *
     * @mbggenerated
     */
    public Integer getIp_cnt() {
        return ip_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.ip_cnt
     *
     * @param ip_cnt the value for session_day_stats.ip_cnt
     *
     * @mbggenerated
     */
    public void setIp_cnt(Integer ip_cnt) {
        this.ip_cnt = ip_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.session_duration_sum
     *
     * @return the value of session_day_stats.session_duration_sum
     *
     * @mbggenerated
     */
    public Integer getSession_duration_sum() {
        return session_duration_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.session_duration_sum
     *
     * @param session_duration_sum the value for session_day_stats.session_duration_sum
     *
     * @mbggenerated
     */
    public void setSession_duration_sum(Integer session_duration_sum) {
        this.session_duration_sum = session_duration_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.pageview_cnt_sum
     *
     * @return the value of session_day_stats.pageview_cnt_sum
     *
     * @mbggenerated
     */
    public Integer getPageview_cnt_sum() {
        return pageview_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.pageview_cnt_sum
     *
     * @param pageview_cnt_sum the value for session_day_stats.pageview_cnt_sum
     *
     * @mbggenerated
     */
    public void setPageview_cnt_sum(Integer pageview_cnt_sum) {
        this.pageview_cnt_sum = pageview_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.page_cnt_sum
     *
     * @return the value of session_day_stats.page_cnt_sum
     *
     * @mbggenerated
     */
    public Integer getPage_cnt_sum() {
        return page_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.page_cnt_sum
     *
     * @param page_cnt_sum the value for session_day_stats.page_cnt_sum
     *
     * @mbggenerated
     */
    public void setPage_cnt_sum(Integer page_cnt_sum) {
        this.page_cnt_sum = page_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.eventdo_cnt_sum
     *
     * @return the value of session_day_stats.eventdo_cnt_sum
     *
     * @mbggenerated
     */
    public Integer getEventdo_cnt_sum() {
        return eventdo_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.eventdo_cnt_sum
     *
     * @param eventdo_cnt_sum the value for session_day_stats.eventdo_cnt_sum
     *
     * @mbggenerated
     */
    public void setEventdo_cnt_sum(Integer eventdo_cnt_sum) {
        this.eventdo_cnt_sum = eventdo_cnt_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_day_stats.user_session_cnt
     *
     * @return the value of session_day_stats.user_session_cnt
     *
     * @mbggenerated
     */
    public Double getUser_session_cnt() {
        return user_session_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_day_stats.user_session_cnt
     *
     * @param user_session_cnt the value for session_day_stats.user_session_cnt
     *
     * @mbggenerated
     */
    public void setUser_session_cnt(Double user_session_cnt) {
        this.user_session_cnt = user_session_cnt;
    }
}