package com.edreaminfo.cbas.orm.model;

import java.util.Date;

public class SessionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.session_id
     *
     * @mbggenerated
     */
    private Integer session_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.Session_start_datetime
     *
     * @mbggenerated
     */
    private Date session_start_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.channel_id
     *
     * @mbggenerated
     */
    private Integer channel_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.version_id
     *
     * @mbggenerated
     */
    private Integer version_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.phone_type
     *
     * @mbggenerated
     */
    private String phone_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session_log.os
     *
     * @mbggenerated
     */
    private String os;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.id
     *
     * @return the value of session_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.id
     *
     * @param id the value for session_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.session_id
     *
     * @return the value of session_log.session_id
     *
     * @mbggenerated
     */
    public Integer getSession_id() {
        return session_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.session_id
     *
     * @param session_id the value for session_log.session_id
     *
     * @mbggenerated
     */
    public void setSession_id(Integer session_id) {
        this.session_id = session_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.Session_start_datetime
     *
     * @return the value of session_log.Session_start_datetime
     *
     * @mbggenerated
     */
    public Date getSession_start_datetime() {
        return session_start_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.Session_start_datetime
     *
     * @param session_start_datetime the value for session_log.Session_start_datetime
     *
     * @mbggenerated
     */
    public void setSession_start_datetime(Date session_start_datetime) {
        this.session_start_datetime = session_start_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.user_id
     *
     * @return the value of session_log.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.user_id
     *
     * @param user_id the value for session_log.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.ip
     *
     * @return the value of session_log.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.ip
     *
     * @param ip the value for session_log.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.channel_id
     *
     * @return the value of session_log.channel_id
     *
     * @mbggenerated
     */
    public Integer getChannel_id() {
        return channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.channel_id
     *
     * @param channel_id the value for session_log.channel_id
     *
     * @mbggenerated
     */
    public void setChannel_id(Integer channel_id) {
        this.channel_id = channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.version_id
     *
     * @return the value of session_log.version_id
     *
     * @mbggenerated
     */
    public Integer getVersion_id() {
        return version_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.version_id
     *
     * @param version_id the value for session_log.version_id
     *
     * @mbggenerated
     */
    public void setVersion_id(Integer version_id) {
        this.version_id = version_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.phone_type
     *
     * @return the value of session_log.phone_type
     *
     * @mbggenerated
     */
    public String getPhone_type() {
        return phone_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.phone_type
     *
     * @param phone_type the value for session_log.phone_type
     *
     * @mbggenerated
     */
    public void setPhone_type(String phone_type) {
        this.phone_type = phone_type == null ? null : phone_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session_log.os
     *
     * @return the value of session_log.os
     *
     * @mbggenerated
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session_log.os
     *
     * @param os the value for session_log.os
     *
     * @mbggenerated
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }
}