package com.edreaminfo.cbas.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SessionDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table session_details
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table session_details
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table session_details
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public SessionDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table session_details
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSession_idIsNull() {
            addCriterion("session_id is null");
            return (Criteria) this;
        }

        public Criteria andSession_idIsNotNull() {
            addCriterion("session_id is not null");
            return (Criteria) this;
        }

        public Criteria andSession_idEqualTo(Integer value) {
            addCriterion("session_id =", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idNotEqualTo(Integer value) {
            addCriterion("session_id <>", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idGreaterThan(Integer value) {
            addCriterion("session_id >", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("session_id >=", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idLessThan(Integer value) {
            addCriterion("session_id <", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idLessThanOrEqualTo(Integer value) {
            addCriterion("session_id <=", value, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idIn(List<Integer> values) {
            addCriterion("session_id in", values, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idNotIn(List<Integer> values) {
            addCriterion("session_id not in", values, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idBetween(Integer value1, Integer value2) {
            addCriterion("session_id between", value1, value2, "session_id");
            return (Criteria) this;
        }

        public Criteria andSession_idNotBetween(Integer value1, Integer value2) {
            addCriterion("session_id not between", value1, value2, "session_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Integer value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Integer value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Integer value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Integer> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtIsNull() {
            addCriterion("session_start_dt is null");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtIsNotNull() {
            addCriterion("session_start_dt is not null");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtEqualTo(Date value) {
            addCriterion("session_start_dt =", value, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtNotEqualTo(Date value) {
            addCriterion("session_start_dt <>", value, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtGreaterThan(Date value) {
            addCriterion("session_start_dt >", value, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtGreaterThanOrEqualTo(Date value) {
            addCriterion("session_start_dt >=", value, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtLessThan(Date value) {
            addCriterion("session_start_dt <", value, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtLessThanOrEqualTo(Date value) {
            addCriterion("session_start_dt <=", value, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtIn(List<Date> values) {
            addCriterion("session_start_dt in", values, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtNotIn(List<Date> values) {
            addCriterion("session_start_dt not in", values, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtBetween(Date value1, Date value2) {
            addCriterion("session_start_dt between", value1, value2, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_start_dtNotBetween(Date value1, Date value2) {
            addCriterion("session_start_dt not between", value1, value2, "session_start_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtIsNull() {
            addCriterion("session_end_dt is null");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtIsNotNull() {
            addCriterion("session_end_dt is not null");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtEqualTo(Date value) {
            addCriterion("session_end_dt =", value, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtNotEqualTo(Date value) {
            addCriterion("session_end_dt <>", value, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtGreaterThan(Date value) {
            addCriterion("session_end_dt >", value, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtGreaterThanOrEqualTo(Date value) {
            addCriterion("session_end_dt >=", value, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtLessThan(Date value) {
            addCriterion("session_end_dt <", value, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtLessThanOrEqualTo(Date value) {
            addCriterion("session_end_dt <=", value, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtIn(List<Date> values) {
            addCriterion("session_end_dt in", values, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtNotIn(List<Date> values) {
            addCriterion("session_end_dt not in", values, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtBetween(Date value1, Date value2) {
            addCriterion("session_end_dt between", value1, value2, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_end_dtNotBetween(Date value1, Date value2) {
            addCriterion("session_end_dt not between", value1, value2, "session_end_dt");
            return (Criteria) this;
        }

        public Criteria andSession_durationIsNull() {
            addCriterion("session_duration is null");
            return (Criteria) this;
        }

        public Criteria andSession_durationIsNotNull() {
            addCriterion("session_duration is not null");
            return (Criteria) this;
        }

        public Criteria andSession_durationEqualTo(Integer value) {
            addCriterion("session_duration =", value, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationNotEqualTo(Integer value) {
            addCriterion("session_duration <>", value, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationGreaterThan(Integer value) {
            addCriterion("session_duration >", value, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationGreaterThanOrEqualTo(Integer value) {
            addCriterion("session_duration >=", value, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationLessThan(Integer value) {
            addCriterion("session_duration <", value, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationLessThanOrEqualTo(Integer value) {
            addCriterion("session_duration <=", value, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationIn(List<Integer> values) {
            addCriterion("session_duration in", values, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationNotIn(List<Integer> values) {
            addCriterion("session_duration not in", values, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationBetween(Integer value1, Integer value2) {
            addCriterion("session_duration between", value1, value2, "session_duration");
            return (Criteria) this;
        }

        public Criteria andSession_durationNotBetween(Integer value1, Integer value2) {
            addCriterion("session_duration not between", value1, value2, "session_duration");
            return (Criteria) this;
        }

        public Criteria andPageview_cntIsNull() {
            addCriterion("pageview_cnt is null");
            return (Criteria) this;
        }

        public Criteria andPageview_cntIsNotNull() {
            addCriterion("pageview_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andPageview_cntEqualTo(Integer value) {
            addCriterion("pageview_cnt =", value, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntNotEqualTo(Integer value) {
            addCriterion("pageview_cnt <>", value, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntGreaterThan(Integer value) {
            addCriterion("pageview_cnt >", value, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntGreaterThanOrEqualTo(Integer value) {
            addCriterion("pageview_cnt >=", value, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntLessThan(Integer value) {
            addCriterion("pageview_cnt <", value, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntLessThanOrEqualTo(Integer value) {
            addCriterion("pageview_cnt <=", value, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntIn(List<Integer> values) {
            addCriterion("pageview_cnt in", values, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntNotIn(List<Integer> values) {
            addCriterion("pageview_cnt not in", values, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntBetween(Integer value1, Integer value2) {
            addCriterion("pageview_cnt between", value1, value2, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPageview_cntNotBetween(Integer value1, Integer value2) {
            addCriterion("pageview_cnt not between", value1, value2, "pageview_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntIsNull() {
            addCriterion("page_cnt is null");
            return (Criteria) this;
        }

        public Criteria andPage_cntIsNotNull() {
            addCriterion("page_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andPage_cntEqualTo(Integer value) {
            addCriterion("page_cnt =", value, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntNotEqualTo(Integer value) {
            addCriterion("page_cnt <>", value, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntGreaterThan(Integer value) {
            addCriterion("page_cnt >", value, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_cnt >=", value, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntLessThan(Integer value) {
            addCriterion("page_cnt <", value, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntLessThanOrEqualTo(Integer value) {
            addCriterion("page_cnt <=", value, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntIn(List<Integer> values) {
            addCriterion("page_cnt in", values, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntNotIn(List<Integer> values) {
            addCriterion("page_cnt not in", values, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntBetween(Integer value1, Integer value2) {
            addCriterion("page_cnt between", value1, value2, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andPage_cntNotBetween(Integer value1, Integer value2) {
            addCriterion("page_cnt not between", value1, value2, "page_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntIsNull() {
            addCriterion("eventdo_cnt is null");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntIsNotNull() {
            addCriterion("eventdo_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntEqualTo(Integer value) {
            addCriterion("eventdo_cnt =", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntNotEqualTo(Integer value) {
            addCriterion("eventdo_cnt <>", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntGreaterThan(Integer value) {
            addCriterion("eventdo_cnt >", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntGreaterThanOrEqualTo(Integer value) {
            addCriterion("eventdo_cnt >=", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntLessThan(Integer value) {
            addCriterion("eventdo_cnt <", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntLessThanOrEqualTo(Integer value) {
            addCriterion("eventdo_cnt <=", value, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntIn(List<Integer> values) {
            addCriterion("eventdo_cnt in", values, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntNotIn(List<Integer> values) {
            addCriterion("eventdo_cnt not in", values, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntBetween(Integer value1, Integer value2) {
            addCriterion("eventdo_cnt between", value1, value2, "eventdo_cnt");
            return (Criteria) this;
        }

        public Criteria andEventdo_cntNotBetween(Integer value1, Integer value2) {
            addCriterion("eventdo_cnt not between", value1, value2, "eventdo_cnt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table session_details
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table session_details
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}