package com.edreaminfo.cbas.orm.model;

public class UserTypeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_type_info.user_type_id
     *
     * @mbggenerated
     */
    private Integer user_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_type_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_type_info.user_type_id
     *
     * @return the value of user_type_info.user_type_id
     *
     * @mbggenerated
     */
    public Integer getUser_type_id() {
        return user_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_type_info.user_type_id
     *
     * @param user_type_id the value for user_type_info.user_type_id
     *
     * @mbggenerated
     */
    public void setUser_type_id(Integer user_type_id) {
        this.user_type_id = user_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_type_info.name
     *
     * @return the value of user_type_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_type_info.name
     *
     * @param name the value for user_type_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}