package com.edreaminfo.cbas.orm.model;

import java.util.ArrayList;
import java.util.List;

public class UserWeekStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public UserWeekStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWeekIsNull() {
            addCriterion("week is null");
            return (Criteria) this;
        }

        public Criteria andWeekIsNotNull() {
            addCriterion("week is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEqualTo(Integer value) {
            addCriterion("week =", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotEqualTo(Integer value) {
            addCriterion("week <>", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThan(Integer value) {
            addCriterion("week >", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("week >=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThan(Integer value) {
            addCriterion("week <", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThanOrEqualTo(Integer value) {
            addCriterion("week <=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekIn(List<Integer> values) {
            addCriterion("week in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotIn(List<Integer> values) {
            addCriterion("week not in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekBetween(Integer value1, Integer value2) {
            addCriterion("week between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("week not between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Integer value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Integer value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Integer value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Integer> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andLife_weeksIsNull() {
            addCriterion("life_weeks is null");
            return (Criteria) this;
        }

        public Criteria andLife_weeksIsNotNull() {
            addCriterion("life_weeks is not null");
            return (Criteria) this;
        }

        public Criteria andLife_weeksEqualTo(Integer value) {
            addCriterion("life_weeks =", value, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksNotEqualTo(Integer value) {
            addCriterion("life_weeks <>", value, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksGreaterThan(Integer value) {
            addCriterion("life_weeks >", value, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksGreaterThanOrEqualTo(Integer value) {
            addCriterion("life_weeks >=", value, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksLessThan(Integer value) {
            addCriterion("life_weeks <", value, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksLessThanOrEqualTo(Integer value) {
            addCriterion("life_weeks <=", value, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksIn(List<Integer> values) {
            addCriterion("life_weeks in", values, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksNotIn(List<Integer> values) {
            addCriterion("life_weeks not in", values, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksBetween(Integer value1, Integer value2) {
            addCriterion("life_weeks between", value1, value2, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andLife_weeksNotBetween(Integer value1, Integer value2) {
            addCriterion("life_weeks not between", value1, value2, "life_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksIsNull() {
            addCriterion("active_weeks is null");
            return (Criteria) this;
        }

        public Criteria andActive_weeksIsNotNull() {
            addCriterion("active_weeks is not null");
            return (Criteria) this;
        }

        public Criteria andActive_weeksEqualTo(Integer value) {
            addCriterion("active_weeks =", value, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksNotEqualTo(Integer value) {
            addCriterion("active_weeks <>", value, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksGreaterThan(Integer value) {
            addCriterion("active_weeks >", value, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksGreaterThanOrEqualTo(Integer value) {
            addCriterion("active_weeks >=", value, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksLessThan(Integer value) {
            addCriterion("active_weeks <", value, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksLessThanOrEqualTo(Integer value) {
            addCriterion("active_weeks <=", value, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksIn(List<Integer> values) {
            addCriterion("active_weeks in", values, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksNotIn(List<Integer> values) {
            addCriterion("active_weeks not in", values, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksBetween(Integer value1, Integer value2) {
            addCriterion("active_weeks between", value1, value2, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andActive_weeksNotBetween(Integer value1, Integer value2) {
            addCriterion("active_weeks not between", value1, value2, "active_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksIsNull() {
            addCriterion("inactive_weeks is null");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksIsNotNull() {
            addCriterion("inactive_weeks is not null");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksEqualTo(Integer value) {
            addCriterion("inactive_weeks =", value, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksNotEqualTo(Integer value) {
            addCriterion("inactive_weeks <>", value, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksGreaterThan(Integer value) {
            addCriterion("inactive_weeks >", value, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksGreaterThanOrEqualTo(Integer value) {
            addCriterion("inactive_weeks >=", value, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksLessThan(Integer value) {
            addCriterion("inactive_weeks <", value, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksLessThanOrEqualTo(Integer value) {
            addCriterion("inactive_weeks <=", value, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksIn(List<Integer> values) {
            addCriterion("inactive_weeks in", values, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksNotIn(List<Integer> values) {
            addCriterion("inactive_weeks not in", values, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksBetween(Integer value1, Integer value2) {
            addCriterion("inactive_weeks between", value1, value2, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andInactive_weeksNotBetween(Integer value1, Integer value2) {
            addCriterion("inactive_weeks not between", value1, value2, "inactive_weeks");
            return (Criteria) this;
        }

        public Criteria andTurn_activeIsNull() {
            addCriterion("turn_active is null");
            return (Criteria) this;
        }

        public Criteria andTurn_activeIsNotNull() {
            addCriterion("turn_active is not null");
            return (Criteria) this;
        }

        public Criteria andTurn_activeEqualTo(Byte value) {
            addCriterion("turn_active =", value, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeNotEqualTo(Byte value) {
            addCriterion("turn_active <>", value, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeGreaterThan(Byte value) {
            addCriterion("turn_active >", value, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeGreaterThanOrEqualTo(Byte value) {
            addCriterion("turn_active >=", value, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeLessThan(Byte value) {
            addCriterion("turn_active <", value, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeLessThanOrEqualTo(Byte value) {
            addCriterion("turn_active <=", value, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeIn(List<Byte> values) {
            addCriterion("turn_active in", values, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeNotIn(List<Byte> values) {
            addCriterion("turn_active not in", values, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeBetween(Byte value1, Byte value2) {
            addCriterion("turn_active between", value1, value2, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_activeNotBetween(Byte value1, Byte value2) {
            addCriterion("turn_active not between", value1, value2, "turn_active");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveIsNull() {
            addCriterion("turn_inactive is null");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveIsNotNull() {
            addCriterion("turn_inactive is not null");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveEqualTo(Byte value) {
            addCriterion("turn_inactive =", value, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveNotEqualTo(Byte value) {
            addCriterion("turn_inactive <>", value, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveGreaterThan(Byte value) {
            addCriterion("turn_inactive >", value, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveGreaterThanOrEqualTo(Byte value) {
            addCriterion("turn_inactive >=", value, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveLessThan(Byte value) {
            addCriterion("turn_inactive <", value, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveLessThanOrEqualTo(Byte value) {
            addCriterion("turn_inactive <=", value, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveIn(List<Byte> values) {
            addCriterion("turn_inactive in", values, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveNotIn(List<Byte> values) {
            addCriterion("turn_inactive not in", values, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveBetween(Byte value1, Byte value2) {
            addCriterion("turn_inactive between", value1, value2, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andTurn_inactiveNotBetween(Byte value1, Byte value2) {
            addCriterion("turn_inactive not between", value1, value2, "turn_inactive");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusIsNull() {
            addCriterion("loyal_status is null");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusIsNotNull() {
            addCriterion("loyal_status is not null");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusEqualTo(Byte value) {
            addCriterion("loyal_status =", value, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusNotEqualTo(Byte value) {
            addCriterion("loyal_status <>", value, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusGreaterThan(Byte value) {
            addCriterion("loyal_status >", value, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusGreaterThanOrEqualTo(Byte value) {
            addCriterion("loyal_status >=", value, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusLessThan(Byte value) {
            addCriterion("loyal_status <", value, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusLessThanOrEqualTo(Byte value) {
            addCriterion("loyal_status <=", value, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusIn(List<Byte> values) {
            addCriterion("loyal_status in", values, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusNotIn(List<Byte> values) {
            addCriterion("loyal_status not in", values, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusBetween(Byte value1, Byte value2) {
            addCriterion("loyal_status between", value1, value2, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLoyal_statusNotBetween(Byte value1, Byte value2) {
            addCriterion("loyal_status not between", value1, value2, "loyal_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusIsNull() {
            addCriterion("lost_status is null");
            return (Criteria) this;
        }

        public Criteria andLost_statusIsNotNull() {
            addCriterion("lost_status is not null");
            return (Criteria) this;
        }

        public Criteria andLost_statusEqualTo(Byte value) {
            addCriterion("lost_status =", value, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusNotEqualTo(Byte value) {
            addCriterion("lost_status <>", value, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusGreaterThan(Byte value) {
            addCriterion("lost_status >", value, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusGreaterThanOrEqualTo(Byte value) {
            addCriterion("lost_status >=", value, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusLessThan(Byte value) {
            addCriterion("lost_status <", value, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusLessThanOrEqualTo(Byte value) {
            addCriterion("lost_status <=", value, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusIn(List<Byte> values) {
            addCriterion("lost_status in", values, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusNotIn(List<Byte> values) {
            addCriterion("lost_status not in", values, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusBetween(Byte value1, Byte value2) {
            addCriterion("lost_status between", value1, value2, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLost_statusNotBetween(Byte value1, Byte value2) {
            addCriterion("lost_status not between", value1, value2, "lost_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusIsNull() {
            addCriterion("lostall_status is null");
            return (Criteria) this;
        }

        public Criteria andLostall_statusIsNotNull() {
            addCriterion("lostall_status is not null");
            return (Criteria) this;
        }

        public Criteria andLostall_statusEqualTo(Byte value) {
            addCriterion("lostall_status =", value, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusNotEqualTo(Byte value) {
            addCriterion("lostall_status <>", value, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusGreaterThan(Byte value) {
            addCriterion("lostall_status >", value, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusGreaterThanOrEqualTo(Byte value) {
            addCriterion("lostall_status >=", value, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusLessThan(Byte value) {
            addCriterion("lostall_status <", value, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusLessThanOrEqualTo(Byte value) {
            addCriterion("lostall_status <=", value, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusIn(List<Byte> values) {
            addCriterion("lostall_status in", values, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusNotIn(List<Byte> values) {
            addCriterion("lostall_status not in", values, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusBetween(Byte value1, Byte value2) {
            addCriterion("lostall_status between", value1, value2, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andLostall_statusNotBetween(Byte value1, Byte value2) {
            addCriterion("lostall_status not between", value1, value2, "lostall_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusIsNull() {
            addCriterion("new_status is null");
            return (Criteria) this;
        }

        public Criteria andNew_statusIsNotNull() {
            addCriterion("new_status is not null");
            return (Criteria) this;
        }

        public Criteria andNew_statusEqualTo(Byte value) {
            addCriterion("new_status =", value, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusNotEqualTo(Byte value) {
            addCriterion("new_status <>", value, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusGreaterThan(Byte value) {
            addCriterion("new_status >", value, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusGreaterThanOrEqualTo(Byte value) {
            addCriterion("new_status >=", value, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusLessThan(Byte value) {
            addCriterion("new_status <", value, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusLessThanOrEqualTo(Byte value) {
            addCriterion("new_status <=", value, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusIn(List<Byte> values) {
            addCriterion("new_status in", values, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusNotIn(List<Byte> values) {
            addCriterion("new_status not in", values, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusBetween(Byte value1, Byte value2) {
            addCriterion("new_status between", value1, value2, "new_status");
            return (Criteria) this;
        }

        public Criteria andNew_statusNotBetween(Byte value1, Byte value2) {
            addCriterion("new_status not between", value1, value2, "new_status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_week_status
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}