package com.edreaminfo.cbas.orm.model;

import java.util.Date;

public class UserDayLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.dt
     *
     * @mbggenerated
     */
    private Date dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.user_id
     *
     * @mbggenerated
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.ip_cnt
     *
     * @mbggenerated
     */
    private Integer ip_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.session_cnt
     *
     * @mbggenerated
     */
    private Integer session_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.pageview_cnt
     *
     * @mbggenerated
     */
    private Integer pageview_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.eventdo_cnt
     *
     * @mbggenerated
     */
    private Integer eventdo_cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_day_log.session_duration_sum
     *
     * @mbggenerated
     */
    private Integer session_duration_sum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.id
     *
     * @return the value of user_day_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.id
     *
     * @param id the value for user_day_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.dt
     *
     * @return the value of user_day_log.dt
     *
     * @mbggenerated
     */
    public Date getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.dt
     *
     * @param dt the value for user_day_log.dt
     *
     * @mbggenerated
     */
    public void setDt(Date dt) {
        this.dt = dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.user_id
     *
     * @return the value of user_day_log.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.user_id
     *
     * @param user_id the value for user_day_log.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.ip_cnt
     *
     * @return the value of user_day_log.ip_cnt
     *
     * @mbggenerated
     */
    public Integer getIp_cnt() {
        return ip_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.ip_cnt
     *
     * @param ip_cnt the value for user_day_log.ip_cnt
     *
     * @mbggenerated
     */
    public void setIp_cnt(Integer ip_cnt) {
        this.ip_cnt = ip_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.session_cnt
     *
     * @return the value of user_day_log.session_cnt
     *
     * @mbggenerated
     */
    public Integer getSession_cnt() {
        return session_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.session_cnt
     *
     * @param session_cnt the value for user_day_log.session_cnt
     *
     * @mbggenerated
     */
    public void setSession_cnt(Integer session_cnt) {
        this.session_cnt = session_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.pageview_cnt
     *
     * @return the value of user_day_log.pageview_cnt
     *
     * @mbggenerated
     */
    public Integer getPageview_cnt() {
        return pageview_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.pageview_cnt
     *
     * @param pageview_cnt the value for user_day_log.pageview_cnt
     *
     * @mbggenerated
     */
    public void setPageview_cnt(Integer pageview_cnt) {
        this.pageview_cnt = pageview_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.eventdo_cnt
     *
     * @return the value of user_day_log.eventdo_cnt
     *
     * @mbggenerated
     */
    public Integer getEventdo_cnt() {
        return eventdo_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.eventdo_cnt
     *
     * @param eventdo_cnt the value for user_day_log.eventdo_cnt
     *
     * @mbggenerated
     */
    public void setEventdo_cnt(Integer eventdo_cnt) {
        this.eventdo_cnt = eventdo_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_day_log.session_duration_sum
     *
     * @return the value of user_day_log.session_duration_sum
     *
     * @mbggenerated
     */
    public Integer getSession_duration_sum() {
        return session_duration_sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_day_log.session_duration_sum
     *
     * @param session_duration_sum the value for user_day_log.session_duration_sum
     *
     * @mbggenerated
     */
    public void setSession_duration_sum(Integer session_duration_sum) {
        this.session_duration_sum = session_duration_sum;
    }
}