package com.edreaminfo.cbas.orm.model;

public class VersionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.version_id
     *
     * @mbggenerated
     */
    private Integer version_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.version_cn
     *
     * @mbggenerated
     */
    private String version_cn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.id
     *
     * @return the value of version_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.id
     *
     * @param id the value for version_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.version_id
     *
     * @return the value of version_info.version_id
     *
     * @mbggenerated
     */
    public Integer getVersion_id() {
        return version_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.version_id
     *
     * @param version_id the value for version_info.version_id
     *
     * @mbggenerated
     */
    public void setVersion_id(Integer version_id) {
        this.version_id = version_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.version_cn
     *
     * @return the value of version_info.version_cn
     *
     * @mbggenerated
     */
    public String getVersion_cn() {
        return version_cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.version_cn
     *
     * @param version_cn the value for version_info.version_cn
     *
     * @mbggenerated
     */
    public void setVersion_cn(String version_cn) {
        this.version_cn = version_cn == null ? null : version_cn.trim();
    }
}