package com.edreaminfo.cbas.orm.model;

import java.util.ArrayList;
import java.util.List;

public class VersionInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table version_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table version_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table version_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public VersionInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table version_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersion_idIsNull() {
            addCriterion("version_id is null");
            return (Criteria) this;
        }

        public Criteria andVersion_idIsNotNull() {
            addCriterion("version_id is not null");
            return (Criteria) this;
        }

        public Criteria andVersion_idEqualTo(Integer value) {
            addCriterion("version_id =", value, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idNotEqualTo(Integer value) {
            addCriterion("version_id <>", value, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idGreaterThan(Integer value) {
            addCriterion("version_id >", value, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("version_id >=", value, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idLessThan(Integer value) {
            addCriterion("version_id <", value, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idLessThanOrEqualTo(Integer value) {
            addCriterion("version_id <=", value, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idIn(List<Integer> values) {
            addCriterion("version_id in", values, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idNotIn(List<Integer> values) {
            addCriterion("version_id not in", values, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idBetween(Integer value1, Integer value2) {
            addCriterion("version_id between", value1, value2, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_idNotBetween(Integer value1, Integer value2) {
            addCriterion("version_id not between", value1, value2, "version_id");
            return (Criteria) this;
        }

        public Criteria andVersion_cnIsNull() {
            addCriterion("version_cn is null");
            return (Criteria) this;
        }

        public Criteria andVersion_cnIsNotNull() {
            addCriterion("version_cn is not null");
            return (Criteria) this;
        }

        public Criteria andVersion_cnEqualTo(String value) {
            addCriterion("version_cn =", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnNotEqualTo(String value) {
            addCriterion("version_cn <>", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnGreaterThan(String value) {
            addCriterion("version_cn >", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnGreaterThanOrEqualTo(String value) {
            addCriterion("version_cn >=", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnLessThan(String value) {
            addCriterion("version_cn <", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnLessThanOrEqualTo(String value) {
            addCriterion("version_cn <=", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnLike(String value) {
            addCriterion("version_cn like", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnNotLike(String value) {
            addCriterion("version_cn not like", value, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnIn(List<String> values) {
            addCriterion("version_cn in", values, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnNotIn(List<String> values) {
            addCriterion("version_cn not in", values, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnBetween(String value1, String value2) {
            addCriterion("version_cn between", value1, value2, "version_cn");
            return (Criteria) this;
        }

        public Criteria andVersion_cnNotBetween(String value1, String value2) {
            addCriterion("version_cn not between", value1, value2, "version_cn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table version_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table version_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}