package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.EventdoPairDayStats;
import com.edreaminfo.cbas.orm.model.EventdoPairDayStatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventdoPairDayStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int countByExample(EventdoPairDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int deleteByExample(EventdoPairDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int insert(EventdoPairDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int insertSelective(EventdoPairDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    List<EventdoPairDayStats> selectByExample(EventdoPairDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    EventdoPairDayStats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EventdoPairDayStats record, @Param("example") EventdoPairDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EventdoPairDayStats record, @Param("example") EventdoPairDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventdoPairDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventdo_pair_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EventdoPairDayStats record);
}