package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.EventInfo;
import com.edreaminfo.cbas.orm.model.EventInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int countByExample(EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int deleteByExample(EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int insert(EventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int insertSelective(EventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    List<EventInfo> selectByExample(EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    EventInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EventInfo record, @Param("example") EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EventInfo record, @Param("example") EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EventInfo record);
}