package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.PageviewDayStats;
import com.edreaminfo.cbas.orm.model.PageviewDayStatsExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PageviewDayStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int countByExample(PageviewDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int deleteByExample(PageviewDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int insert(PageviewDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int insertSelective(PageviewDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    List<PageviewDayStats> selectByExample(PageviewDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    PageviewDayStats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PageviewDayStats record, @Param("example") PageviewDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PageviewDayStats record, @Param("example") PageviewDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PageviewDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageview_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PageviewDayStats record);
    
	//input: startDay, endDay (channel_id, version_id)
    //return key: pageId, pvCount, sessionCount, eventdoCountSum, pvQuitSum, pvDurationSum, dayCount
	List<Map<String, Object>> selectPageStatisticGroupByPageId(Map<String, Object> selectMap);

	//input: startDay, endDay (page_id, channel_id, version_id)
	//return key: targetDay, pvCount, sessionCount, eventdoCountSum, pvQuitSum, pvDurationSum, pageCount
	List<Map<String, Object>> selectPageStatisticGroupByTargetDay(Map<String, Object> selectMap);
}