package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.RelationEventgroupPage;
import com.edreaminfo.cbas.orm.model.RelationEventgroupPageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationEventgroupPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int countByExample(RelationEventgroupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int deleteByExample(RelationEventgroupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int insert(RelationEventgroupPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int insertSelective(RelationEventgroupPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    List<RelationEventgroupPage> selectByExample(RelationEventgroupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    RelationEventgroupPage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelationEventgroupPage record, @Param("example") RelationEventgroupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelationEventgroupPage record, @Param("example") RelationEventgroupPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelationEventgroupPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_pagegroup_page
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelationEventgroupPage record);
}