package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.RelationBusinessPagegroup;
import com.edreaminfo.cbas.orm.model.RelationBusinessPagegroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationBusinessPagegroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int countByExample(RelationBusinessPagegroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int deleteByExample(RelationBusinessPagegroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int insert(RelationBusinessPagegroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int insertSelective(RelationBusinessPagegroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    List<RelationBusinessPagegroup> selectByExample(RelationBusinessPagegroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    RelationBusinessPagegroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelationBusinessPagegroup record, @Param("example") RelationBusinessPagegroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelationBusinessPagegroup record, @Param("example") RelationBusinessPagegroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelationBusinessPagegroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_pagegroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelationBusinessPagegroup record);
}