package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.RelationEventgroupEvent;
import com.edreaminfo.cbas.orm.model.RelationEventgroupEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationEventgroupEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int countByExample(RelationEventgroupEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int deleteByExample(RelationEventgroupEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int insert(RelationEventgroupEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int insertSelective(RelationEventgroupEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    List<RelationEventgroupEvent> selectByExample(RelationEventgroupEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    RelationEventgroupEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelationEventgroupEvent record, @Param("example") RelationEventgroupEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelationEventgroupEvent record, @Param("example") RelationEventgroupEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelationEventgroupEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_eventgroup_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelationEventgroupEvent record);
}