package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.RelationBusinessEventgroup;
import com.edreaminfo.cbas.orm.model.RelationBusinessEventgroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationBusinessEventgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int countByExample(RelationBusinessEventgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int deleteByExample(RelationBusinessEventgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int insert(RelationBusinessEventgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int insertSelective(RelationBusinessEventgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    List<RelationBusinessEventgroup> selectByExample(RelationBusinessEventgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    RelationBusinessEventgroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelationBusinessEventgroup record, @Param("example") RelationBusinessEventgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelationBusinessEventgroup record, @Param("example") RelationBusinessEventgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelationBusinessEventgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_eventgroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelationBusinessEventgroup record);
}