package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.RelationBusinessEvent;
import com.edreaminfo.cbas.orm.model.RelationBusinessEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationBusinessEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int countByExample(RelationBusinessEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int deleteByExample(RelationBusinessEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int insert(RelationBusinessEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int insertSelective(RelationBusinessEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    List<RelationBusinessEvent> selectByExample(RelationBusinessEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    RelationBusinessEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelationBusinessEvent record, @Param("example") RelationBusinessEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelationBusinessEvent record, @Param("example") RelationBusinessEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelationBusinessEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_business_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelationBusinessEvent record);
}