package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.SessionLog;
import com.edreaminfo.cbas.orm.model.SessionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int countByExample(SessionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int deleteByExample(SessionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int insert(SessionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int insertSelective(SessionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    List<SessionLog> selectByExample(SessionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    SessionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SessionLog record, @Param("example") SessionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SessionLog record, @Param("example") SessionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SessionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SessionLog record);
}