package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.SessionHourStats;
import com.edreaminfo.cbas.orm.model.SessionHourStatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionHourStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int countByExample(SessionHourStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int deleteByExample(SessionHourStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int insert(SessionHourStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int insertSelective(SessionHourStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    List<SessionHourStats> selectByExample(SessionHourStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    SessionHourStats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SessionHourStats record, @Param("example") SessionHourStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SessionHourStats record, @Param("example") SessionHourStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SessionHourStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_hour_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SessionHourStats record);
}