package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.SessionDayStats;
import com.edreaminfo.cbas.orm.model.SessionDayStatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionDayStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int countByExample(SessionDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int deleteByExample(SessionDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int insert(SessionDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int insertSelective(SessionDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    List<SessionDayStats> selectByExample(SessionDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    SessionDayStats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SessionDayStats record, @Param("example") SessionDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SessionDayStats record, @Param("example") SessionDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SessionDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SessionDayStats record);
}