package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.UserWeekStatus;
import com.edreaminfo.cbas.orm.model.UserWeekStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWeekStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int countByExample(UserWeekStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int deleteByExample(UserWeekStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int insert(UserWeekStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int insertSelective(UserWeekStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    List<UserWeekStatus> selectByExample(UserWeekStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    UserWeekStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserWeekStatus record, @Param("example") UserWeekStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserWeekStatus record, @Param("example") UserWeekStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserWeekStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_week_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserWeekStatus record);
}