package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.UserDayStats;
import com.edreaminfo.cbas.orm.model.UserDayStatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDayStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int countByExample(UserDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int deleteByExample(UserDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int insert(UserDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int insertSelective(UserDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    List<UserDayStats> selectByExample(UserDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    UserDayStats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDayStats record, @Param("example") UserDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDayStats record, @Param("example") UserDayStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDayStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_stats
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDayStats record);
}