package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.UserDayLog;
import com.edreaminfo.cbas.orm.model.UserDayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int countByExample(UserDayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int deleteByExample(UserDayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int insert(UserDayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int insertSelective(UserDayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    List<UserDayLog> selectByExample(UserDayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    UserDayLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDayLog record, @Param("example") UserDayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDayLog record, @Param("example") UserDayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDayLog record);
}