package com.edreaminfo.cbas.orm.dao;

import com.edreaminfo.cbas.orm.model.UserDayStatus;
import com.edreaminfo.cbas.orm.model.UserDayStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDayStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int countByExample(UserDayStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int deleteByExample(UserDayStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int insert(UserDayStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int insertSelective(UserDayStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    List<UserDayStatus> selectByExample(UserDayStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    UserDayStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDayStatus record, @Param("example") UserDayStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDayStatus record, @Param("example") UserDayStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDayStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_day_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDayStatus record);
}