package com.edreaminfo.tspm.orm.dao;

import com.edreaminfo.tspm.orm.model.CxBasStaff;
import com.edreaminfo.tspm.orm.model.CxBasStaffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CxBasStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cx_bas_staff
     *
     * @mbggenerated
     */
    int countByExample(CxBasStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cx_bas_staff
     *
     * @mbggenerated
     */
    int deleteByExample(CxBasStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cx_bas_staff
     *
     * @mbggenerated
     */
    int insert(CxBasStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cx_bas_staff
     *
     * @mbggenerated
     */
    int insertSelective(CxBasStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cx_bas_staff
     *
     * @mbggenerated
     */
    List<CxBasStaff> selectByExample(CxBasStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cx_bas_staff
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CxBasStaff record, @Param("example") CxBasStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cx_bas_staff
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CxBasStaff record, @Param("example") CxBasStaffExample example);
}